### base Url
GET http://localhost:3000 HTTP/1.1

### Create User
POST http://localhost:3000/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email": "4@asd2.com",
    "password": "1234",
    "password2": "1234"
}

### Find users by Email
GET http://localhost:3000/auth?email=4@asd2.com HTTP/1.1
Content-Type: application/json

### Find a User
GET http://localhost:3000/auth/1 HTTP/1.1
Content-Type: application/json


### Delete a User
DELETE  http://localhost:3000/auth/4 HTTP/1.1
Content-Type: application/json


### Update User
Patch http://localhost:3000/auth/update/1 HTTP/1.1
Content-Type: application/json

{
    "email": "4@asd2.com",
    "password": "1212312334"
}